import "../policies.css";
import type { Metadata } from "next";

const EFFECTIVE_DATE = "January 30, 2026";
const CONTACT_EMAIL = "support@adviceapp.net";
const APP_NAME = "AdVice";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "Terms governing the use of AdVice, including community rules and limitations.",
};

export default function TermsPage() {
  return (
    <main className="page">
      <div className="container">
        {/* Header */}
        <div className="header">
          <div className="brand">
            Ad<span>V</span>ice
          </div>
          <div className="h1">Terms & Conditions</div>
          <div className="sub">
            Effective date: {EFFECTIVE_DATE}. By using {APP_NAME}, you agree to
            these Terms.
          </div>
        </div>

        {/* Service */}
        <section className="card">
          <div className="h2">The Service</div>
          <p className="p">
            {APP_NAME} provides tools for tracking habits or vices, optional
            community features, and AI-generated guidance intended to support
            self-improvement and awareness. By downloading or using the Advice app, these terms will automatically apply to you
          </p>
        </section>

        {/* No professional advice */}
        <section className="card">
          <div className="h2">No Professional Advice</div>
          <p className="p">
            {APP_NAME} is provided for informational and self-improvement
            purposes only. Content generated by the app, including AI insights,
            is not medical, psychological, legal, or professional advice.
          </p>
          <p className="p">
            You are responsible for how you use the information provided. If you
            need professional support, seek help from a qualified professional.
          </p>
        </section>

        {/* Accounts */}
        <section className="card">
          <div className="h2">Accounts & Responsibility</div>
          <ul className="ul">
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You agree to provide accurate information to the best of your knowledge.</li>
            <li>You are responsible for all activity that occurs under your account.</li>
          </ul>
        </section>

        {/* Community */}
        <section className="card">
          <div className="h2">Community Use</div>
          <ul className="ul">
            <li>Be respectful and supportive of others.</li>
            <li>No harassment, bullying, hate speech, or threats.</li>
            <li>No sharing of personal or private information.</li>
            <li>No spam, scams, or impersonation.</li>
            <li>Report content that violates community standards.</li>
          </ul>
          <p className="p">
            We reserve the right to remove content or restrict accounts that
            violate these guidelines.
          </p>
        </section>

        {/* User content */}
        <section className="card">
          <div className="h2">User Content</div>
          <p className="p">
            You retain ownership of content you create or submit. By posting
            content in {APP_NAME}, you grant us a limited, non-exclusive license
            to host, display, and distribute that content within the app for the
            purpose of operating the service.
          </p>
        </section>

        {/* AI */}
        <section className="card">
          <div className="h2">AI-Generated Content</div>
          <p className="p">
            AI-generated insights are automated and may not be accurate,
            complete, or appropriate for every situation. You acknowledge that
            such content is provided without guarantees.
          </p>
        </section>

        {/* Termination */}
        <section className="card">
          <div className="h2">Account Termination</div>
          <p className="p">
            We may suspend or terminate access to {APP_NAME} if use of the
            service violates these Terms or threatens the safety of other users
            or the platform.
          </p>
          <p className="p">
            You may delete your account at any time through the app’s settings.
          </p>
        </section>

        {/* Disclaimers */}
        <section className="card">
          <div className="h2">Disclaimers & Limitation of Liability</div>
          <p className="p">
            {APP_NAME} is provided “as is” without warranties of any kind. To the
            maximum extent permitted by law, we are not liable for indirect,
            incidental, special, or consequential damages arising from use of
            the service.
          </p>
        </section>

        {/* Changes */}
        <section className="card">
          <div className="h2">Changes to These Terms</div>
          <p className="p">
            We may update these Terms from time to time. Continued use of the app
            after changes become effective means you accept the updated Terms.
          </p>
        </section>

        {/* Contact */}
        <section className="card">
          <div className="h2">Contact</div>
          <p className="p">
            If you have questions about these Terms, contact us at{" "}
            <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
          </p>
        </section>

        <div className="footer">
          These Terms are provided for general informational purposes.
        </div>
      </div>
    </main>
  );
}
