import "../policies.css";
import type { Metadata } from "next";

const EFFECTIVE_DATE = "January 30, 2026";
const CONTACT_EMAIL = "support@adviceapp.net";
const APP_NAME = "AdVice";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "Terms governing the use of AdVice, including community rules and limitations.",
};

export default function TermsPage() {
  return (
    <main className="page">
      <div className="container">
        {/* Header */}
        <div className="header">
          <div className="brand">
            Ad<span>V</span>ice
          </div>
          <div className="h1">Terms & Conditions</div>
          <div className="sub">
            Effective date: {EFFECTIVE_DATE}. By using {APP_NAME}, you agree to
            these Terms.
          </div>
        </div>

        {/* Service */}
        <section className="card">
          <div className="h2">The Service</div>
          <p className="p">
            {APP_NAME} provides tools for tracking habits or vices, optional
            community features, and AI-generated guidance intended to support
            self-improvement and awareness. By downloading or using the AdVice app, these terms will automatically apply to you
          </p>
        </section>

        {/* No professional advice */}
        <section className="card">
          <div className="h2">No Professional Advice</div>
          <p className="p">
            {APP_NAME} is provided for informational and self-improvement
            purposes only. Content generated by the app, including AI insights,
            is not medical, psychological, legal, or professional advice.
          </p>
          <p className="p">
            You are responsible for how you use the information provided. If you
            need professional support, seek help from a qualified professional.
          </p>
        </section>

        <section className="card">
  <div className="h2">Eligibility</div>
  <p className="p">
    You must be at least 13 years of age to use the Services. By accessing or
    using the Services, you represent and warrant that you meet this age
    requirement.
  </p>
</section>


        {/* Accounts */}
        <section className="card">
          <div className="h2">Accounts & Responsibility</div>
          <ul className="ul">
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You agree to provide accurate information to the best of your knowledge.</li>
            <li>You are responsible for all activity that occurs under your account.</li>
          </ul>
        </section>

        {/* Community */}
        <section className="card">
          <div className="h2">Community Use</div>
          <ul className="ul">
            <li>Be respectful and supportive of others.</li>
            <li>No harassment, bullying, hate speech, or threats.</li>
            <li>No sharing of personal or private information.</li>
            <li>No spam, scams, or impersonation.</li>
            <li>No sexually explicit content or exploitation.</li>
<li>No content that promotes self-harm or suicide.</li>
<li>No illegal activity, including buying/selling illegal drugs.</li>
<li>No sharing content involving minors in a sexual context (zero tolerance).</li>

            <li>Report content that violates community standards.</li>
          </ul>
<p className="p">
  We may remove content, restrict visibility, or suspend accounts at our
  discretion to enforce these Terms and maintain a safe community.
</p>

        </section>

        <section className="card">
  <div className="h2">Reporting & Enforcement</div>
  <p className="p">
    If you encounter content or behavior that violates these Terms, you can
    report it through the app. We may investigate reports and take action,
    including content removal or account restrictions, to maintain platform
    safety.
  </p>
</section>


        {/* User content */}
        <section className="card">
          <div className="h2">User Content</div>
          <p className="p">
            You retain ownership of content you create or submit. By posting
            content in {APP_NAME}, you grant us a limited, non-exclusive license
            to host, display, and distribute that content within the app for the
            purpose of operating the service.
          </p>
        </section>
        

        <section className="card">
  <div className="h2">Subscriptions & Billing</div>
  <p className="p">
    Certain features of {APP_NAME} may require a paid subscription. Payment will
    be charged to your Apple ID account at confirmation of purchase.
    Subscriptions may auto-renew unless canceled at least 24 hours before the
    end of the current billing period. Auto-renewal may be turned off in your
    Apple ID account settings. You can manage or cancel your subscription in
    your Apple ID account settings. Payments and refunds are handled by Apple in
    accordance with Apple’s policies.
  </p>
</section>


        {/* AI */}
        <section className="card">
          <div className="h2">AI-Generated Content</div>
          <p className="p">
            AI-generated insights are automated and may not be accurate,
            complete, or appropriate for every situation. You acknowledge that
            such content is provided without guarantees.
          </p>
        </section>

        {/* Termination */}
        <section className="card">
          <div className="h2">Account Termination</div>
          <p className="p">
            We may suspend or terminate access to {APP_NAME} if use of the
            service violates these Terms or threatens the safety of other users
            or the platform.
          </p>
          <p className="p">
            You may delete your account at any time through the app’s settings.
          </p>
        </section>

        {/* Disclaimers */}
        <section className="card">
          <div className="h2">Disclaimers & Limitation of Liability</div>
          <p className="p">
            {APP_NAME} is provided “as is” without warranties of any kind. To the
            maximum extent permitted by law, we are not liable for indirect,
            incidental, special, or consequential damages arising from use of
            the service.


          </p>
        </section>

        <section className="card">
  <div className="h2">Third-Party Services</div>
  <p className="p">
    {APP_NAME} relies on third-party services to operate (such as cloud storage,
    subscriptions, and AI processing). Your use of these features may involve
    processing of data by these providers in accordance with our Privacy Policy
    and their own terms and privacy policies.
  </p>
</section>


        {/* Changes */}
        <section className="card">
          <div className="h2">Changes to These Terms</div>
          <p className="p">
            We may update these Terms from time to time. Continued use of the app
            after changes become effective means you accept the updated Terms.
          </p>
        </section>

        {/* Contact */}
        <section className="card">
          <div className="h2">Contact</div>
          <p className="p">
            If you have questions about these Terms, contact us at{" "}
            <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
          </p>
        </section>

        <div className="footer">
          These Terms are provided for general informational purposes.
        </div>
      </div>
    </main>
  );
}
